on:
  push:
    branches:
      - master

name: Building V8

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} / v8-${{ matrix.version }}

    strategy:
      fail-fast: false
      matrix:
        distro: [ 'centos-8', 'debian-9', 'debian-10' ]
        version: [ '8.3.110.13', '8.6.395.17' ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          docker build --build-arg v8_version=${{ matrix.version }} ${{ matrix.distro }} -t mybuild

      - name: copy
        run: |
          docker run -d --name myrun mybuild
          docker cp myrun:/v8-${{ matrix.version }}-static.tar.xz .
          docker stop myrun

      - name: store
        uses: actions/upload-artifact@v2
        with:
          name: v8-${{ matrix.version }}-${{ matrix.distro }}
          path: v8-${{ matrix.version }}-static.tar.xz
